apiVersion: v1
kind: Service
metadata:
  labels:
    app: collector
  name: collector
spec:
  ports:
  - name: "4317"
    port: 4317
    targetPort: 4317
  - name: "4318"
    port: 4318
    targetPort: 4318
  selector:
    app: collector
